language: cpp
compiler:
  - clang

addons:
  apt:
    packages:
      - g++-multilib
      - lib32z1-dev

env:
  global:
    - HL2SDK_VERSION=sdk2013
    - MMSOURCE_VERSION=1.10-dev
    - SOURCEMOD_VERSION=1.8-dev

install:
  - git clone https://github.com/alliedmodders/sourcemod.git -b $SOURCEMOD_VERSION --depth 1 --recursive $TRAVIS_BUILD_DIR/../sourcemod
  - git clone https://github.com/alliedmodders/metamod-source.git -b $MMSOURCE_VERSION --depth 1 $TRAVIS_BUILD_DIR/../metamod-source
  - git clone https://github.com/alliedmodders/hl2sdk.git -b $HL2SDK_VERSION --depth 1 $TRAVIS_BUILD_DIR/../hl2sdk-$HL2SDK_VERSION
  - git clone https://github.com/alliedmodders/ambuild.git --depth 1 $TRAVIS_BUILD_DIR/../ambuild
  - cd $TRAVIS_BUILD_DIR/../ambuild && python setup.py build && sudo python setup.py install
  - cd $TRAVIS_BUILD_DIR/../sourcemod && mkdir build && cd build && python ../configure.py --no-mysql --sdks=present && ambuild

script:
  - mkdir $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
  - python ../configure.py --sdks=present
  - ambuild

before_deploy:
  - tar -czf sm-ripext-${TRAVIS_TAG}-linux.tar.gz -C package/ addons/

deploy:
  provider: releases
  api_key:
    secure: ChnbDcb0/joPrzRCmv23AOe5z9oRLYRNnkalSqwAru9T+MC60kaWtm12wl/XGsrSPGavd3X7Zx4kjjYBrSwKDic7ld2l15e2i2ihvnXVxe1ezR5Y8f5hBEGTzSevYULrKOCV3oKPc9caPcE0KN3Yy0GYKCOIlN2mBdU3VSUtswUyM/1cAqXR8RN+yaZv0MTmS9xRn9ciEEGplZ3ewR/sXe8bLXcg99FHLnKneEqkA8C9kCLWpwEmIY6i9FhAnZO4GDTuqCtlsvNzHsgzmcvxdglJ6jnB4Z2GMlO4dOGlzBeOvDLDpR40dqg8wZoSkBCy6ZdSEGkVcAYkq6bBVrOsT19wQmWe7kynM/+WxdhBOm6o0/5ohWK68syg5rx8QBAP52UNC3U6BlyeyJc377QSW8BaqBoaAZMSh66i0GcnBCz5/stFdU9L2WKTr1pGPltAPTFHRbD+lZRsErjBcu3ayb15UOqM5XxSvfnKn4QpEVA33eBT89rxS/w9uy7qw4ZUocxmgqkxY1/ODbdJXfIf7wtxYYUYAbwmaxU5rWwjAoLpSU9eP8/fXPhDgCb6M1pkA2j/FyFjR4yWg3vT8buLAcOYk8spmdyQVx1x9d6z9w9aH+EyCrEeXQYZHGnoCIcDCKn7+FkmkbYuuVJMSRJvwtRIwcFxMzaCHctaon0Q/Eg=
  file: sm-ripext-${TRAVIS_TAG}-linux.tar.gz
  skip_cleanup: true
  on:
    tags: true
